language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

before_script:
    - chmod +x gradlew
#Build, and run tests
script: "./gradlew build testDebug"
sudo: false

# cache gradle deps (important considering travis tends to fail here)
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# upload an APK afterwards
addons:
  artifacts:
    s3_region: "us-east-1"
    debug: true
    paths:
    - ./app/build/outputs/apk/
