language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

before_script:
    - chmod +x gradlew
#Build, and run tests
script: "./gradlew build testDebug"
sudo: false
addons:
  artifacts:
    s3_region: "us-east-1"
    debug: true
    paths:
    - ./app/build/outputs/apk/*.apk